# Generated by Django 3.1.5 on 2021-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0002_auto_20210202_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
