# Generated by Django 3.1.5 on 2021-02-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0004_auto_20210209_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.SmallIntegerField()),
                ('dislikes', models.SmallIntegerField()),
                ('is_reply', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_articles.article')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_articles.articlecomment')),
            ],
        ),
    ]
