# Generated by Django 3.1.5 on 2021-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0005_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='text',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='dislikes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='likes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
