# Generated by Django 3.1.5 on 2021-02-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0007_article_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
