# Generated by Django 3.1.5 on 2021-02-26 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0008_auto_20210226_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_reports',
            field=models.ManyToManyField(related_name='reports_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
